### ISSUE TITLE
Finally a free Flux pulid on Colab!

### ISSUE THREAD

**Issue by youisgood** [LucipherDev/Flux.1-dev-PuLID-jupyter#1]
This is very good as we can use pulid in free colab. Thank you very much! Good job bro!

But can you make an option to use pulid flux 0.9.0 as the model, because for me the 0.9.0 is far better than the last one (0.9.1). Maybe something like combobox or pull down menu. And it could be better if we can put the negative prompts. It will make this pulid version more badass! Please consider this boss. Thank you very much!

**Comment by LucipherDev** [comment]
Thank you for your feedback! I just added the option to choose pulid versions.

**Comment by youisgood** [comment]
Thank you boss! How about the negative prompts?
